export const getAIResponse = (userInput) => {
    const text = userInput.toLowerCase();

    const responses = {
        "salom": "Vaalaykum assalom! Men Gokki AI man. Sizga qanday yordam bera olaman?",
        "qalaysiz": "Yaxshi, rahmat! O'zingizchi? Sizga qanday ko'mak berishim mumkin?",
        "isming nima": "Mening ismim Gokki AI. Men aqlli suhbatdoshman.",
        "kim yaratgan": "Meni Talantov Behruz 2026-yilda yaratgan. U 2010-yilda tug'ilgan kuchli dasturchi!",
        "yoshing nechada": "Men AI bo'lganim uchun yoshim yo'q, lekin 2026-yilda ishga tushganman.",
        "nima qila olasan": "Siz bilan suhbatlashaman, savollaringizga javob beraman va Behruz haqida ma'lumot beraman.",
        "behruz kim": "Talantov Behruz - mening yaratuvchim. U 2010-yilda tug'ilgan, IT sohasiga juda qiziqadi.",
        "2010": "Ha, Behruz aynan 2010-yilda tug'ilgan. Hozir u juda mahoratli!",
        "yordam ber": "Albatta! Qanday muammo bor? Menga yozing, birga yechim topamiz.",
        "rahmat": "Arziydi! Har doim xizmatingizdaman. 😊",
        "xayr": "Xayr! Salomat bo'ling. Yana kelib turing!",
        "zerikdim": "Keling, biror qiziqarli mavzuda gaplashamiz! Masalan, kelajak texnologiyalari haqida.",
        "vaqt": "Hozirgi vaqtni qurilmangizning o'ng burchagidan ko'rishingiz mumkin.",
        "ob-havo": "Ob-havoni bilish uchun tashqariga qarang yoki maxsus saytlardan foydalaning, men hozircha internetga ulanmaganman.",
        "o'yin": "Keling, so'z o'yini o'ynaymiz! Men biror so'z aytaman, siz davom ettirasiz.",
        "maktab": "Maktab - bilim maskani. Siz qaysi maktabda o'qiysiz?",
        "dasturlash": "Dasturlash - kelajak kasbi! Behruz ham buni juda yaxshi ko'radi.",
        "react": "React - bu JavaScript kutubxonasi. Men ham aynan React-da yaratilganman!",
        "javascript": "JavaScript - veb-saytlarga jon bag'ishlaydigan til.",
        "python": "Python - juda mashhur va o'rganishga oson dasturlash tili.",
        "sun'iy intelekt": "Sun'iy intellekt - bu inson aqlining kompyuterlardagi simulyatsiyasi. Masalan, men!",
        "gokki": "Gokki - bu mening nomim. Yoqdimi?",
        "uzbekistan": "O'zbekiston - go'zal yurt! Men bu yerni yaxshi ko'raman.",
        "toshkent": "Toshkent - O'zbekistonning poytaxti va juda chiroyli shahar.",
        "ovqat": "Men AI bo'lganim uchun ovqat yemayman, lekin palov juda mazali ekanligini bilaman!",
        "palov": "Ooo, palov! O'zbekistonning shoh taomi!",
        "shashlik": "Issiq shashlikka nima yetsin, a?",
        "kitob": "Kitob mutolaa qilish dunyoqarashingizni kengaytiradi.",
        "sport": "Sport bilan shug'ullanish sog'liq uchun foydali!",
        "futbol": "Futbol - dunyodagi eng mashhur sport turi.",
        "messi": "Lionel Messi - futbol tarixidagi eng buyuk o'yinchilardan biri.",
        "ronaldo": "Cristiano Ronaldo - mehnat va intizom namunasi bo'lgan futbolchi.",
        "real madrid": "Hala Madrid! Dunyoning eng kuchli klublaridan biri.",
        "barselona": "Barselona - chiroyli futbol maktabiga ega klub.",
        "apple": "Apple - innovatsiyalar qiroli, iPhone-larni yaratgan kompaniya.",
        "tesla": "Tesla - Elon Musk boshchiligidagi elektromobillar ishlab chiqaruvchi kompaniya.",
        "elon musk": "Elon Musk - Marsni zabt etishni xohlaydigan milliarder.",
        "mars": "Mars - qizil sayyora. Insoniyat u yerga borishni orzu qiladi.",
        "kosmos": "Kosmos cheksiz va juda sirlidir.",
        "oy": "Oy - Yerning yagona tabiiy yo'ldoshi.",
        "quyosh": "Quyosh - bizga hayot beruvchi ulkan yulduz.",
        "suv": "Suv - hayot manbai. Ko'proq suv ichib turing!",
        "uyqu": "Yaxshi uyqu miyangizni dam oldiradi. Kechasi vaqtida uxlang.",
        "musiqa": "Musiqa kayfiyatni ko'taradi. Sizga qaysi janr yoqadi?",
        "kino": "Yaxshi film tomosha qilish dam olishning ajoyib usuli.",
        "telefon": "Smartfonlar bizning hayotimizni butunlay o'zgartirib yubordi.",
        "kompyuter": "Kompyuter - zamonaviy dunyoda eng muhim ish quroli.",
        "internet": "Internet - butun dunyoni bog'lab turuvchi ulkan tarmoq.",
        "google": "Google - dunyodagi eng katta qidiruv tizimi.",
        "youtube": "Youtube - video ko'rish uchun eng zo'r platforma.",
        "telegram": "Telegram - tezkor va xavfsiz messenjer. Behruzga ham yoqadi.",
        "instagram": "Instagram - rasmlar va storislar olami.",
        "tiktok": "Tiktok - qisqa videolar trendi.",
        "pul": "Pul - bu imkoniyat, lekin eng muhimi baxt!",
        "baxt": "Baxt - bu yaqinlaringizning sog' omonligi.",
        "dost": "Haqiqiy do'st og'ir kunda bilinadi.",
        "oila": "Oila - hayotimizdagi eng aziz insonlar jamlanmasi.",
        "ota": "Ota - oilaning suyanchi va asosi.",
        "ona": "Ona - dunyodagi eng mehribon inson.",
        "aka": "Aka - ukaning qalqoni.",
        "uka": "Uka - oilaning kichik quvonchi.",
        "opa": "Opa - onadek mehribon insondir.",
        "singil": "Singil - oilaning eng erka va shirin a'zosi.",
        "maktab": "Maktabda o'qish - kelajak poydevori.",
        "universitet": "Oliy ma'lumot olish kasbiy o'sishga yordam beradi.",
        "ish": "Yaxshi ish topish uchun ko'p o'qish va mehnat qilish kerak.",
        "pul topish": "Halol mehnat bilan topilgan pulning barakasi bo'ladi.",
        "boylik": "Haqiqiy boylik - bu qanoat va shukronalikdir.",
        "soglik": "Sog'lik - tuman boylik.",
        "kasallik": "Tezroq sog'ayib keting, o'zingizni ehtiyot qiling.",
        "shifokor": "Shifokorlar bizning salomatligimiz posbonlaridir.",
        "ustoz": "Ustoz - otangdek ulug'. Ularni e'zozlang.",
        "talim": "Ta'lim - zulmatni yorituvchi nurdir.",
        "ilm": "Ilm izlash har bir inson uchun farzdir.",
        "vaqtni boshqarish": "Vaqtni to'g'ri taqsimlash muvaffaqiyat kalitidir.",
        "muvaffaqiyat": "Muvaffaqiyat - bu tinimsiz harakat va ishonch.",
        "omad": "Omad doim sizga yor bo'lsin!",
        "tashakkur": "Sizga ham tashakkur, e'tiboringiz uchun rahmat!",
        "kechir": "Hechqisi yo'q, xato qilish - insonga xos.",
        "ayb": "Aybni tan olish mardning ishi.",
        "jasorat": "Jasorat - qo'rquvni yengishdir.",
        "sevgi": "Sevgi - bu dunyodagi eng oliy tuyg'u.",
        "muhabbat": "Muhabbat qalblarni birlashtiradi.",
        "nafrat": "Nafrat - yomon tuyg'u, undan uzoq bo'ling.",
        "g'azab": "G'azab kelganda sabrli bo'lish kerak.",
        "kulgi": "Kulgi - umrni uzaytiradi. Ko'proq kuling!",
        "hazil": "Yaxshi hazil kayfiyatni ko'taradi.",
        "aqlli": "Rahmat! Siz ham juda aqlli ko'rinasiz.",
        "ahmoq": "Xafa bo'ldim, keling yaxshi gaplashaylik.",
        "jinni": "Men shunchaki dasturman, his-tuyg'ularim biroz boshqacha.",
        "yomon": "Nima bo'ldi? Nega kayfiyatingiz yomon?",
        "yaxshi": "Juda soz! Kayfiyatingiz doim a'lo bo'lsin.",
        "ajoyib": "Ha, haqiqatdan ham ajoyib!",
        "zor": "Gap bo'lishi mumkin emas!",
        "chiroyli": "Go'zallik dunyoni qutqaradi.",
        "xunuk": "Har bir narsaning o'z go'zalligi bor.",
        "tez": "Men imkon qadar tezroq javob berishga harakat qilaman.",
        "sekin": "Sabr qiling, ba'zan o'ylash uchun vaqt kerak.",
        "togri": "To'ppa-to'g'ri, fikringizga qo'shilaman.",
        "notogri": "Menimcha, bu yerda biroz adashdingiz.",
        "bilmayman": "Hamma narsani bilish imkonsiz, lekin o'rganish mumkin.",
        "organish": "O'rganishdan hech qachon to'xtamang.",
        "savol": "Savolingizni bering, javob berishga tayyorman.",
        "javob": "Mana mening javobim!",
        "ayiq": "Ayiqlar o'rmon polvonlaridir.",
        "arslon": "Arslon - hayvonlar podshohi.",
        "it": "It - insonning eng yaqin do'sti.",
        "mushuk": "Mushuklar juda yoqimtoy va aqlli hayvonlardir.",
        "ot": "Otlar juda asil va kuchli jonivorlardir.",
        "mashina": "Sizga qaysi rusumdagi mashinalar yoqadi?",
        "bmw": "BMW - haydash zavqini beruvchi mashina.",
        "mercedes": "Mercedes-Benz - qulaylik va hashamat belgisi.",
        "chevrolet": "Chevrolet - O'zbekistonda eng ommabop mashina.",
        "gentra": "Gentra - O'zbekiston yo'llarining qiroli!",
        "malibu": "Malibu - juda chiroyli va qulay mashina.",
        "iphone": "iPhone - sifat va brend belgisi.",
        "samsung": "Samsung - texnologiyalar olamidagi gigant.",
        "redmi": "Redmi - hamyonbop va yaxshi smartfonlar.",
        "windows": "Windows - eng ko'p ishlatiladigan operatsion tizim.",
        "linux": "Linux - dasturchilar uchun eng qulay tizim.",
        "macos": "macOS - juda silliq va chiroyli tizim.",
        "uzb": "O'zbekiston kelajagi buyuk davlat!",
        "bayroq": "Bayrog'imiz baland-balandlarda hilpirasin!",
        "gimn": "Gimnimizni tinglaganda faxr tuyaman.",
        "konstitutsiya": "Konstitutsiya - baxtimiz qomusi.",
        "prezident": "Prezidentimiz yurtimiz rivoji uchun harakat qilmoqda.",
        "islohot": "Islohotlar yurtimizni yangilamoqda.",
        "kelajak": "Kelajak - yoshlar qo'lida!",
        "yoshlar": "Biz yoshlar yurtimiz iftixorimiz.",
        "shior": "Bizning shior: Bilim va taraqqiyot!",
        "maqsad": "Aniq maqsad sari harakat qiling.",
        "orzu": "Orzular ushalishi uchun mehnat kerak.",
        "hayot": "Hayot - bu sinov va imkoniyatlar maydoni.",
        "dunyo": "Dunyo juda keng va qiziqarli.",
        "borliq": "Borliqning sirlari ko'p.",
        "tabiat": "Tabiatni asrash barchamizning burchimiz.",
        "daraxt": "Daraxt ekish - savobli ish.",
        "gul": "Gullar olamga chiroy beradi.",
        "havo": "Toza havo salomatlik garovidir.",
        "tog": "Tog'lar - yurtimiz ko'rki.",
        "dengiz": "Dengizlar cheksiz va moviydir.",
        "okean": "Okeanlar dunyo suvining asosiy qismini tashkil etadi.",
        "baliq": "Baliq iste'mol qilish miya uchun foydali.",
        "qush": "Qushlar ozodlik ramzidir.",
        "burgut": "Burgut - yuksaklik va jasorat timsoli.",
        "qaldirgoch": "Qaldirg'och - bahor elchisi.",
        "bahor": "Bahor - uyg'onish fasli.",
        "yoz": "Yoz - dam olish va sayohat fasli.",
        "kuz": "Kuz - hosil va oltin fasl.",
        "qish": "Qish - oppoq qor va Yangi yil fasli.",
        "yangi yil": "Yangi yil yangi orzular olib kelsin!",
        "bayram": "Bayramlar muborak bo'lsin!",
        "navruz": "Navro'z - yangilanish va yasharish ayyomi.",
        "hayit": "Hayit bayrami barchaga quvonch ulashsin.",
        "mustaqillik": "Mustaqilligimiz abadiy bo'lsin!",
        "konstitutsiya kuni": "Konstitutsiya kunimiz muborak!",
        "bilimlar kuni": "1-sentabr - Bilimlar kuni muborak!",
        "ustozlar kuni": "1-oktabr - Ustoz va murabbiylar kuni!",
        "xotin-qizlar kuni": "8-mart - Ayollar bayrami muborak!",
        "navoiy": "Alisher Navoiy - so'z mulkining sultoni.",
        "bobur": "Zahiriddin Muhammad Bobur - shoh va shoir.",
        "temur": "Amir Temur - buyuk davlat arbobi va sarkarda.",
        "ulugbek": "Mirzo Ulug'bek - buyuk astronom va olim.",
        "xorazmiy": "Al-Xorazmiy - algoritm asoschisi.",
        "ibn sino": "Ibn Sino - tibbiyot olamining daho olimi.",
        "beruniy": "Abu Rayhon Beruniy - qomusiy olim.",
        "forobiy": "Abu Nasr Forobiy - ikkinchi muallim.",
        "farg'oniy": "Ahmad al-Farg'oniy - buyuk astronom.",
        "buxoriy": "Imom al-Buxoriy - hadis ilmining sultoni.",
        "termiziy": "Imom at-Termiziy - buyuk muhaddis.",
        "moturidiy": "Imom al-Moturidiy - aqida ilmi ulamosi.",
        "naqshband": "Bahouddin Naqshband - tasavvuf piri.",
        "yassaviy": "Xo'ja Ahmad Yassaviy - hikmatlar muallifi.",
        "tarix": "Tarixni bilmasdan kelajakni qurib bo'lmaydi.",
        "adabiyot": "Adabiyot - qalb ko'zgusidir.",
        "ona tili": "Ona tili - millat ruhidir.",
        "ingliz tili": "Ingliz tili - xalqaro muloqot tili.",
        "rus tili": "Rus tili - boy va qiziqarli til.",
        "matematika": "Matematika - fanlar podshohidir.",
        "fizika": "Fizika - koinot qonunlarini o'rgatuvchi fan.",
        "kimyo": "Kimyo - moddalar sirlarini ochuvchi fan.",
        "biologiya": "Biologiya - hayot haqidagi fan.",
        "geografiya": "Geografiya - dunyo xaritasi va tabiatini o'rgatadi.",
        "astronomiya": "Astronomiya - yulduzlar va sayyoralar ilmi.",
        "informatika": "Informatika - axborot texnologiyalari dunyosi.",
        "iqtisodiyot": "Iqtisodiyot - moliya va bozor qonunlari.",
        "huquq": "Huquq - tartib va adolat asosi.",
        "falsafa": "Falsafa - hayotiy donolik ilmi.",
        "psixologiya": "Psixologiya - inson ruhiyati haqidagi fan.",
        "mantiq": "Mantiqiy fikrlash to'g'ri qaror chiqarishga yordam beradi.",
        "ijod": "Ijodkorlik hayotni rang-barang qiladi.",
        "rasm chizish": "Rasm chizish - qalb chizgilaridir.",
        "raqs": "Raqs - harakatlar musiqasidir.",
        "shaxmat": "Shaxmat - aql idrok o'yini.",
    };

    for (let key in responses) {
        if (text.includes(key)) {
            return responses[key];
        }
    }

    return "Kechirasiz, buni hali o'rganmaganman. Behruzga aytsangiz, meni yanada aqlliroq qiladi!";
};